ebitengine/purego

dl_darwin.go
this constant is needed for dlopen to work.
=> add constant RTLD_GLOBAL

syscall.go, syscall_darwin.go, syscall_windows.go
This uses `go:nosplit` to ensure that the stack does not split as discussed in #5. This commit also adds windows support to purego by calling the syscall.Syscall equivalent function.
=> purego: use go:nosplit and map to proper implementation

runtime.go, syscall.go, syscall_darwin.go, syscall_windows.go
this forces the uintptr arguments to escape in SyscallN. When optimizations were enabled Go assumed that the []uintptr argument in SyscallN could be placed on the stack. This is why functions like gl.GenFramebuffersEXT would fail. Although this change forces all of the arguments to be placed on the heap it ensures that no optimizations will remove our precious arguments. This also allows us to only have one implementation inside SyscallN (i.e. syscall_syscall9X). A potential replacement would be //go:cgo_unsafe_args but that can only be used in CGO generated files. There is also //go:uintptrkeepalive although that was not enough to stop the function from failing. That is why I went with //go:uintptrescapes. More information about this pragma can be found on the …
=> purego: add //go:uintptrescapes to SyscallN

runtime.go, sys_darwin_amd64.s, syscall.go, syscall_darwin.go, syscall_windows.go
sys_darwin_amd64.s was pushing the struct pointer to -8(SP) which is a part of the red-zone. We have enough space on the stack to push it above the arguments. Doing so is safer too
=> No red zone

sys_darwin_amd64.s
It appears the Go runtime would occasionally decide to split the stack while the callbackArgs struct was on the unmovable system stack and so the pointer would then point to garbage memory. I did this right on arm64
=> don't split the stack on amd64

objc/objc_runtime_darwin.go, objc/objc_runtime_darwin_test.go, syscall_darwin.go
Ivar or InstanceVariables are like fields in a struct except for Objective-C objects. This PR add support for adding Ivars to classes. It also provides an example of how to use them properly.
This will be needed to fully port glfw to Go
=> add Ivar support and Objc Tests

objc/objc_runtime_darwin_test.go
For testing, a package with the suffix `_test` is preferrable since it prevents accidental white-box testings.
=> objc: change the test package

dlfcn.go
Creating a reflect.SliceHeader is invalid. See https://pkg.go.dev/unsafe#Pointer
=> purego: use a safe way to convert a pointer to a byte slice

syscall.go
this is allowed because SyscallN also uses go:uintptrescapes which forces any uintptr's that are passed to this function to be placed on the heap where a stack split won't affect them. See the [compile docs](https://pkg.go.dev/cmd/compile) for an explanation.
I've tested this change on Oto (amd64 & arm64) without optimizations. I also ran all the test for ebitengine (amd64 & arm64) with OpenGL and Metal.
All this to say, this won't break anything.
This change fixes [Oto#182](https://github.com/hajimehoshi/oto/issues/182).
=> remove go:nosplit at SyscallN

internal/fakecgo/callbacks.go, internal/fakecgo/doc.go, internal/fakecgo/go_libinit.go, internal/fakecgo/go_setenv.go, internal/fakecgo/go_util.go, internal/fakecgo/iscgo.go, internal/fakecgo/libcgo.go, internal/fakecgo/setenv.go, internal/fakecgo/symbols.go, internal/fakecgo/trampolines_amd64.s, internal/fakecgo/trampolines_arm64.s
This enables to build purego with `./...` for Windows.
Closes #28
=> internal/fakecgo: add build tags 'darwin'

.github/workflows/test.yml, dummy.go, internal/abi/dummy.go
Before this change, the package `internal/abi` was ignored by `go mod vendor`
as there was no Go file there. Then building purego failed as `internal/abi`
didn't exist under the `vendor` directory.
This change fixes this issue by adding a dummy Go file to `internal/abi`
and adding an explicit import to it, but with a `dummy` build tag.
I referred a change https://github.com/goccy/go-graphviz/pull/37 for this
hack.
Updates #31
=> internal/abi: add a dummy Go file for go mod vendor

objc/objc_runtime_darwin_test.go, sys_darwin_amd64.s, sys_darwin_arm64.s
There was a TODO that I never tested. This PR updates ExampleIMP to test this behavior and fixes amd64 which was broken.
=> purego: make callbacks with more than 6 arguments work properly on amd64

.github/workflows/test.yml
* A build tag `example` is not used anywhre.
* Building with GOOO=darwin and GOARCH=arm64 are duplicated.
* Tests for iOS were missing
In the ideal world, we should run the binary with ARM64 for macOS,
in addition to the buildings.
=> .githug/workflows: simplify test.yml

objc/objc_runtime_darwin.go
This is needed for [ebitengien#2326](https://github.com/hajimehoshi/ebiten/pull/2326).
Should the `GetProtocol` function return a pointer to Protocol or just Protocol? The Objective-C [runtime](https://developer.apple.com/documentation/objectivec/1418870-objc_getprotocol?language=objc) returns a pointer however there is never a reason for us to need to dereference this pointer so I thought it best to just remove it.
=> objc: add protocol support

dlfcn.go, dlfcn_stubs.s, internal/fakecgo/symbols.go, internal/fakecgo/trampolines_amd64.s, internal/fakecgo/trampolines_arm64.s, internal/fakecgo/trampolines_stubs.s, internal/fakecgo/trampolines_stubs_darwin.s
Using go:linkname and a call5 trampoline function it is possible to remove assembly and push it into Go code. Arguably, it is pretty ugly Go code but functional. Having less assembly means less chance to make a copy paste error and make it easier to port to other architectures
=> Simplify assembly

dlfcn.go
limit usage of SyscallN in favor of RegisterFunc and RegisterLibFunc
=> use RegisterFunc for dlfcn.go

dlfcn.go, dlfcn_darwin.go
This PR does three things.
1. moves the constants under dlfcn_darwin.go since the value is platform specific
2. remove RTLD_DEFAULT which is specific to darwin.
3. adds RTLD_LAZY, RTLD_NOW, RTLD_LOCAL to complete the unix specification
Closes #52
=> Move constants under platform specific file

cgo_darwin.go, dlfcn.go, dummy.go, example/main.go, go_runtime.go, internal/abi/dummy.go, internal/fakecgo/callbacks.go, internal/fakecgo/doc.go, internal/fakecgo/go_libinit.go, internal/fakecgo/go_setenv.go, internal/fakecgo/go_util.go, internal/fakecgo/iscgo.go, internal/fakecgo/libcgo.go, internal/fakecgo/setenv.go, internal/fakecgo/symbols.go, is_ios.go, nocgo_darwin.go, syscall.go
This change drops old build tag comments `// +build`.
=> all: fix build tags

objc/objc_runtime_darwin.go, objc/objc_runtime_darwin_test.go
This PR is based on my comment in #54. It removes all uses of package unsafe from the tests by creating a struct that matches the structure of the Objective-C object.
=> objc: remove unsafe usage from test

syscall_darwin.go
This PR explicitly enumerates which types can be returned from a callback. It also adds support for returning `reflect.Pointer` and `reflect.UnsafePointer`
=> purego: enumerate types that can be returned from callbacks

sys_darwin_amd64.s
On x86-64 R12 is callee-saved which means if we use it in callbackasm1 we MUST preserve its value. We were not doing that so it caused the SIGSEGV to happen in Oto. I replaced R12 with R10 because R10 is caller-saved so we don't need to worry about throwing away the value inside of it.
Source: https://web.stanford.edu/class/archive/cs/cs107/cs107.1174/guide_x86-64.html
Closes #60
=> use R10 instead of R12

dlfcn_stubs.s, internal/fakecgo/go_libinit.go, internal/fakecgo/libcgo.go, internal/fakecgo/symbols.go, internal/fakecgo/trampolines_amd64.s, internal/fakecgo/trampolines_arm64.s
Carrots make the symbol only available in that source file. We need these functions available outside in order for us to call them.
Use the syscall version of Timespec. That way we can clean up our code and not have duplicated types.
=> internal/fakecgo: refactor

sys_darwin_amd64.s
This is a back port of 382f4c69b85482e885511dd001710fd145469a76
Closes #64
=> purego: use R10 instead of R12

func_darwin.go, sys_darwin_amd64.s, sys_darwin_arm64.s
We originally discussed this change (#48) and decided against doing it because r2 usually returns the upper 32bits of a 64bit return value on 32bit platforms. However, on Windows amd64 r2 is actually the float return value.
https://github.com/golang/go/blob/7717ac151ae1556541dddc6a817ac04733f1af44/src/runtime/sys_windows_amd64.s#L66
And there is a TODO for arm64 as well.
https://github.com/golang/go/blob/2cea6cdb6016708e89c9472cdb0504731699681d/src/runtime/sys_windows_arm64.s#L91
Doing this makes supporting float returns easier without having to implement a full C calling convention for RegisterFunc.
=> purego: SyscallN r2 return float

func_darwin.go, sys_darwin_amd64.s, sys_darwin_arm64.s, syscall_darwin.go
This PR adds proper float support into RegisterFunc. It puts the first 8 in registers and the 9th onto the stack. It also checks beforehand that there aren't too many arguments.
=> purego: support float arguments in RegisterFunc

example/main.go, internal/fakecgo/callbacks.go, internal/fakecgo/go_darwin_amd64.go, internal/fakecgo/go_darwin_arm64.go, internal/fakecgo/go_libinit.go, internal/fakecgo/go_setenv.go, internal/fakecgo/go_util.go, internal/fakecgo/trampolines_amd64.s, internal/fakecgo/trampolines_arm64.s
Go 1.20 rewrote the race detector on darwin to be entirely Go. This means that fakecgo was having race functions placed inside of it which made it break. This PR circumvents the race functions by adding `//go:norace` and using closures to skip the ABI wrappers.
Closes #71
=> internal/fakecgo: circumvent Go 1.20's race code

.github/workflows/test.yml
=> .github/workflows: enable go-test with -race for Go 1.21 and the future

objc/objc_runtime_darwin.go
To check that the Go struct has the same size as the Objective-C class subtract the current class's size from the super class's size. This is necessary because the super class's fields are embedded in the child class but are not present in the Go struct. It is fine that the Go struct does not contain the parent's fields because they are not accessible in Go. The +8 is because the child and super class both contain the isa field which the Go struct does have and needs to be counted in this comparison.
=> better error message and padding support

internal/fakecgo/callbacks.go
PR #73 circumvent go 1.20 race mode on darwin. However, the explanation
for using the closure calls are partly wrong, and also not so much clear
about how the trick works.
This commits rework the comments, and adding more detail explanation.
=> internal/fakecgo: correct the explanation of using closure calls

.github/workflows/test.yml, internal/fakecgo/trampolines_darwin_amd64.s, internal/fakecgo/trampolines_linux_amd64.s
#73 broke CGO_ENABLED=0 on Linux amd64 because Linux doesn't need the workaround for //go:norace. This commit separates Darwin and Linux implementations.
Closes #101
=> internal/fakecgo: separate Linux and Darwin trampolines

callback_test.go, libcbtest/callback.c, sys_arm64.s
crosscall2 clobbers FP in the frame record. Use NOFRAME flag for callbackasm1 to disable the assembler generated epilogue that restores the corrupted FP. Save and restore FP manually instead.
=> purego: fix callback crash for arm64

callback_test.go, dlfcn_test.go
With Rosetta on arm64 it was possible to test amd64 just by setting `GOARCH=amd64`. However, since the shared library tests were added it is no longer possible because the default compiler will build for the host architecture and not the cross-compiled (amd64) architecture. This commit tells the C/C++ compiler to build for amd64 when running an amd64 binary. This only effects macOS.
=> purego: enable testing of amd64 with Rosseta on arm64 macOS

dlfcn_test.go
This just reduces local variables and narrows down the scopes of them.
=> purego: clean up some code

syscall_sysv.go
It was possible to create a C callback for a nil function but this shouldn't be possible. This commit makes it so that NewCallback will panic on a nil function.
=> purego: check for nil callback

func.go, go_runtime.go
This rewrites part of the RegisterFunc to have less code escape to the heap. Running the benchmark inside #121 shows a speed increase and alloc decrease.
```
goos: darwin
goarch: arm64
pkg: github.com/ebitengine/purego
BenchmarkCStringC
BenchmarkCStringC-10    	 2294838	       500.3 ns/op	     472 B/op	       8 allocs/op
PASS
```
=> purego: decrease number of allocs in RegisterFunc

examples/objc/main_darwin.go, internal/strings/strings.go, objc/objc_runtime_darwin.go, objc/objc_runtime_darwin_test.go
(now actually safe)
The issued lied in two areas. One, for loop variables take the address instead of copying the memory and taking that address. This should be fixed in 1.22. The second area of issues was caused by memory corruption occurring due to calling C functions inside of closures. 
I've tested this PR with ebitengine and all tested passed on amd64 & arm64 darwin.
Closes #143
=> objc: add safe Objc Classes

.github/workflows/test.yml
Now tests run only on the main branch. This is not good as stable branches are not tested.
=> .github/workflows: reenable tests on branches

callback_test.go, func.go
There wasn't a test for when integers and floats are interleaved in callbacks
=> add test for mix of floats and int arguments in callback

func.go, func_test.go
Sometimes C functions don't return 0 when false, but instead this conversion works.
=> change how bool return values are converted

callback_test.go, func.go, func_test.go, internal/cgo/syscall_cgo_unix.go, objc/objc_runtime_darwin_test.go, sys_amd64.s, sys_arm64.s, syscall.go, syscall_cgo_linux.go, syscall_sysv.go, syscall_windows.go
This increases the max number of arguments to be 15. This is necessary because amd64 puts almost everything on the stack when passing structs. This meant that there wasn't enough room with just 9 arguments to pass all the tests that arm64 has in the struct branch.
=> Increase max argument to 15

buildtest/main.go, cgo.go, dlfcn_darwin.go, dlfcn_freebsd.go, dlfcn_nocgo_darwin.go, dlfcn_nocgo_freebsd.go, dlfcn_nocgo_linux.go, dlfcn_stubs.s, internal/buildtest/main.go, internal/cgo/dlfcn_cgo_unix.go, internal/cgo/syscall_cgo_unix.go
Use the standard Cgo import mechanism when CGO_ENABLED=1. This fixes an issue where sometimes the external linker would fail to add the dlfcn symbols causing a linker error.
Closes #189
=> Fix issue 189

struct_amd64.go, struct_test.go, testdata/structtest/struct_test.c
There was a bug, that caused the last small field, that directly followed a set of small fields that combined into one full machine word, in a struct to not be added to the list of arguments.
It was caused by incorrectly marking that the field that is being processed right now is flushed if processing of previous small field resulted in `val` getting filled enough to be flushed.
In order to avoid similar errors and to have flushing logic at one place I've moved that out into an anonymous function. It should impact performance somewhat, I guess I could just inline it. Would like to hear your opinion on that!
Closes #210
=> Fix Three Small Fields losing the last field

dlfcn_nocgo_linux.go, dlfcn_playground.go
Currently, if a package imports purego in the playground even if none of the functions are called the run will fail with a complaint about unable to link in libdl.so.2. This commit circumvents this by stubbing out the dynamic linking pragmas for the go playground (`//go:build faketime`). This allows building and running apps in the playground that import purego but *doesn't* allow actually calling any of the functions. Currently, it will just die very ungracefully.
Playground: https://go.dev/play/p/t3PK-iTWSl-
Remove the replace in the go.mod to see old behavior.
=> all: allow running programs that import purego in the playground

func.go, objc/objc_runtime_darwin.go, objc/objc_runtime_darwin_test.go, struct_arm64.go, struct_test.go, testdata/structtest/structreturn_test.c
On amd64, there was a crash when calling objc.Send with a struct return type. This was due to calling the wrong objc message send function.
On arm64, if a struct return contained structs that only contained floats it would expect it to be in R8 instead of the expected float registers
Closes #223
=> all: struct return fixes

syscall.go, syscall_cgo_linux.go, syscall_sysv.go, syscall_windows.go
The struct on Cgo non-amd64 and non-arm64 platforms didn't have the struct fields updated. To avoid forgetting to update all the structs I've moved it where every platform shares the same type def.
Closes #228
=> Consolidate struct definition

.github/workflows/test.yml, sys_amd64.s
=> Save R15 before global access

internal/load/load_windows.go, syscall_windows.go
The example still has the dependency on golang.org/x/sys.
Updates #270
#270 
feature
Removes the dependency on golang.org/x/sys from the core.
The example still uses golang.org/x/sys.
=> all: remove dependencies on golang.org/x/sys

examples/libc/main_windows.go, examples/window/main_windows.go, go.mod, go.sum
Closes #270
Closes #270
Bug
This PR moves external dependencies from the entire module.
=> examples: remove depdencies on golang.org/x/sys/windows

func.go
Don't allocate when being called by objc.Send. This is done by just inlining the expansion of the parameters directly into the argument list instead of making a tmp slice.
Use a sync.Pool for syscall15Args struct to save on allocations
=> all: improve memory usage

.github/workflows/test.yml, internal/fakecgo/gen.go, internal/fakecgo/go_libinit.go, internal/fakecgo/libcgo.go, internal/fakecgo/symbols.go
fakecgo runs on the system stack so we shouldn't ever split the stack.
I also updated the size of sigset_t to be the correct size based on the headers. This was needed to make it possible to build with inlining disabled when nosplit was added.
Fixes #287
=> fakecgo: C functions require nosplit

syscall.go
It was unclear how to properly use this function. Add some clarification.
https://github.com/JupiterRider/purego-sdl3/issues/4#issuecomment-2664158178
=> purego: clarify SyscallN usage

.github/scripts/bsd_tests.sh, .github/workflows/test.yml
=> .github/workflows: clean up test.yml

.github/scripts/bsd_tests.sh, .github/workflows/test.yml, README.md
Without `-e` in the shebang `#!/bin/sh`, the script passed even some commands failed and then we missed some errors happened. This change adds `-e` to abort tests with an error code explicitly.
As #305 says, FreeBSD tests w/o optimization fails. This change skips the test temporarilly.
This change also retracts the support of NetBSD temporarily. Let's revert README again after #304 is fixed.
#304 and #305
=> .github/workflows: add -e for FreeBSD test script and skip NetBSD tests

README.md, examples/libc/main.go
This change also updates README by removing NetBSD and adding FreeBSD.
Just cleaning up codes and documents.
=> examples/libc: reorder OSes in alphabetical order

struct_amd64.go, struct_test.go, testdata/structtest/struct_test.c
Relates to https://github.com/hajimehoshi/ebiten/issues/3239
Fixes the bug that uintptr as the only field is not passed to uintptr field on amd64
=> Allow uintptr in struct on amd64

objc/objc_runtime_darwin.go
Updates #225
This fixes a wrong implementation in encodeType for a struct type. A struct type is not used in the real world actually, but this should be a fix for the future.
bug
Updates #225
=> objc: bug fix: wrong implementation in encodeType for a struct

objc/objc_block_darwin.go, objc/objc_block_darwin_test.go, objc/objc_runtime_darwin.go, objc/objc_runtime_darwin_test.go
Solves the issue shown in https://github.com/LucDrenth/purego-handler-segfault.
feature
This PR adds support for Objc blocks. 
Credits and kudos to [K1000000](https://github.com/K1000000), who posted [the original PR](https://github.com/ebitengine/purego/pull/261) to implement this. I just implemented the feedback from that PR, since it got stale and then got closed.
=> Add support for Objc blocks

syscall_sysv.go
This works around the stack growth issue in 05d8da4 while providing the same benefit. The syscall15Args does not escape to the heap for each purego call, reducing memory allocation rate **a lot** for ebitengine!
I am not sure why we need `go:nosplit` at the first place, though. Maybe that can just be removed and this optimization simplified.
Reduces allocations on the hot path
Performance
reduced garbage collection
=> purego: use sync.Pool in syscall_syscall15X with wrapper

.github/workflows/test.yml
As Go 1.25 has been released, add this version for PureGo tests.
n/a
n/a
=> .github/workflows: add Go 1.25
