ebitengine/purego

dl_darwin.go
there is no reason to import strings just for one function
=> remove strings package

objc/objc_runtime_darwin.go, objc/objc_runtime_darwin_test.go
=> objc: rename IMP to NewIMP and _IMP to IMP

.github/workflows/test.yml, callback_go1_16_darwin_arm64.go
I forgot callbackWrapPicker needs to be implemented on arm64
=> arm64 broke

.github/workflows/test.yml
=> .github/workflows: refactoring

objc/objc_runtime_darwin.go
This also adds support for unsafe.Pointer types.
=> make encoding return an error instead of panic

objc/objc_runtime_darwin.go
=> objc: add comment about Objective-C global lock

dlerror.go
Let's wait for the discussion at #107
=> purego: undefine Dlerror for Windows

dlfcn_darwin.go, dlfcn_linux.go, dlfcn_test.go
=> dlfcn: add RTLD_DEFAULT macro value

README.md
=> Document supported platforms and status of project

func.go, func_test.go
Float32 was being converted into float64 which isn't right.
Closes #176
=> purego: fix float returns

func.go
floats and doubles were already implemented in #67 #69 #120 #171 #177
=> Remove WIP comment for float & double

objc/objc_runtime_darwin_test.go
=> objc: use a fullpath for dlopen

.github/workflows/test.yml, internal/fakecgo/asm_amd64.s, sys_amd64.s
=> Align stack to 16 bytes to avoid SIGBUS

objc/objc_runtime_darwin.go, objc/objc_runtime_darwin_test.go
Perhaps, do we need new examples?
=> objc: remove deprecated APIs

.github/ISSUE_TEMPLATE/00-bug.yml, .github/ISSUE_TEMPLATE/01-feature.yml, .github/ISSUE_TEMPLATE/config.yml, .github/PULL_REQUEST_TEMPLATE.md
This is based on Ebitengine's templates for a new issue and a new pull request.
=> .github: add templates

go.mod, go.sum
no issue
maintenance
it updates golang.org/x/sys from v0.19.0 to v0.20.0
=> update golang.org/x/sys from v0.19.0 to v0.20.0

README.md
Closes #242
bug
Update the link for an invitation to the Discord server.
=> all: update the Discord link

func.go, go_runtime.go, internal/fakecgo/gen.go, internal/fakecgo/go_util.go, internal/fakecgo/symbols.go
=> Remove some //go:linkname usages

.github/workflows/test.yml
This change also removes unneeded space chars.
Updates #254 
n/a
Code cleanup
=> .github/workflows: reorder tests

.github/workflows/test.yml, go.mod, go.sum
n/a
Update dependencies versions
n/a
=> all: update dependencies

.github/workflows/test.yml
n/a
Add Go 1.23 to the tests and see what's going on
n/a
=> .github/workflows: add Go 1.23 to the tests

.github/workflows/test.yml
=> .github/workflows: update Go versions for FreeBSD

examples/window/main_windows.go
n/a
n/a
This is just cleaning up.
=> examples/window: replace deprecated functions

README.md, dlerror.go, dlfcn.go
Closes #273
n/a
Clarification on example code for windows in README and adding equivalent windows functions to
=> Clarify Example section and Dl* windows equivalents

dlfcn.go
Updates #273
Updates #273
n/a
n/a
=> purego: mention LoadLibraryEx at Dlopen

func.go
Just after getting a syscall variable from the pool, the variable might be dirty and hold the previous state. Let's clean it explicitly in order to prevent future potential issues.
n/a
n/a
n/a
=> purego: clean syscall after getting from the pool

struct_amd64.go
=> purego: fix typo

README.md
n/a
n/a
Mention that purego supports NetBSD in the README.md
=> README.md: We support NetBSD now!

.github/workflows/test.yml
=> .github/workflows: use 'exclude'

.github/workflows/test.yml, internal/fakecgo/gen.go, internal/fakecgo/go_libinit.go, internal/fakecgo/symbols.go
=> internal/fakecgo: disable race in fakecgo

.github/workflows/test.yml
n/a
n/a
Just update Go versions as a chore.
=> .github/workflows: update Go versions
